/*
 * style.css — IMDb Explorer "Cinematic Scholar" Design System
 * CM3010 Database Coursework
 * Author: Written personally by Ayaan
 * Design tokens generated by Google Stitch MCP (Cinematic Scholar system)
 * CSS implementation written personally by Ayaan based on those tokens.
 */

/* ═══════════════════════════════════════════════════════════
   0. DESIGN TOKENS (from Stitch "Cinematic Scholar" system)
   ═══════════════════════════════════════════════════════════ */
:root {
  /* Colours */
  --clr-bg:           #12121d;
  --clr-surface:      #1f1e2a;
  --clr-surface-hi:   #292935;
  --clr-surface-lo:   #1b1a26;
  --clr-on-surface:   #e3e0f1;
  --clr-on-muted:     #d1c5ac;
  --clr-outline:      #9a9078;
  --clr-gold:         #f5c518;
  --clr-gold-dim:     #f0c110;
  --clr-violet:       #8b5cf6;
  --clr-violet-dim:   #571bc1;
  --clr-teal:         #49dbff;
  --clr-error:        #ffb4ab;
  --clr-glass-border: rgba(255,255,255,0.07);
  --clr-glass-card:   rgba(25,25,35,0.72);

  /* Typography */
  --font-family:      'Inter', system-ui, -apple-system, sans-serif;

  /* Spacing (8px grid) */
  --sp-xs:  0.5rem;   /*  8px */
  --sp-sm:  1rem;     /* 16px */
  --sp-md:  1.5rem;   /* 24px */
  --sp-lg:  3rem;     /* 48px */
  --sp-xl:  5rem;     /* 80px */

  /* Border radius */
  --r-sm:   0.25rem;
  --r-md:   0.5rem;
  --r-lg:   1rem;
  --r-full: 9999px;

  /* Transitions */
  --t-fast: 180ms ease;
  --t-med:  280ms ease;

  /* Max width */
  --max-w: 1280px;
}

/* ═══════════════════════════════════════════════════════════
   1. RESET & BASE
   ═══════════════════════════════════════════════════════════ */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

html {
  scroll-behavior: smooth;
  color-scheme: dark;
}

body {
  font-family:      var(--font-family);
  font-size:        1rem;
  line-height:      1.6;
  color:            var(--clr-on-surface);
  background-color: var(--clr-bg);
  /* Radial glow in corners for depth */
  background-image:
    radial-gradient(ellipse at 0% 0%,   rgba(139,92,246,0.07) 0%, transparent 55%),
    radial-gradient(ellipse at 100% 100%, rgba(245,197,24,0.05) 0%, transparent 55%);
  min-height: 100vh;
}

/* Accessibility: screen-reader only utility */
.sr-only {
  position: absolute; width: 1px; height: 1px;
  padding: 0; margin: -1px; overflow: hidden;
  clip: rect(0,0,0,0); white-space: nowrap; border: 0;
}

a { color: var(--clr-gold); text-decoration: none; transition: color var(--t-fast); }
a:hover, a:focus-visible { color: var(--clr-gold-dim); text-decoration: underline; }
a:focus-visible { outline: 2px solid var(--clr-gold); outline-offset: 3px; border-radius: var(--r-sm); }

img, canvas { max-width: 100%; }

/* Shared container */
.container {
  width: 100%;
  max-width: var(--max-w);
  margin-inline: auto;
  padding-inline: var(--sp-md);
}

/* ═══════════════════════════════════════════════════════════
   2. TYPOGRAPHY UTILITIES
   ═══════════════════════════════════════════════════════════ */
.label-caps {
  font-size:      0.75rem;
  font-weight:    600;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color:          var(--clr-on-muted);
}

.gold-text { color: var(--clr-gold); }

/* ═══════════════════════════════════════════════════════════
   3. NAVBAR
   ═══════════════════════════════════════════════════════════ */
.navbar {
  position:         sticky;
  top:              0;
  z-index:          100;
  background:       rgba(15,15,26,0.72);
  backdrop-filter:  blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border-bottom:    1px solid var(--clr-glass-border);
}

.navbar__inner {
  display:         flex;
  align-items:     center;
  justify-content: space-between;
  gap:             var(--sp-md);
  height:          70px;
}

.navbar__logo {
  font-size:   1.2rem;
  font-weight: 800;
  color:       var(--clr-gold);
  display:     flex;
  align-items: center;
  gap:         0.4rem;
  text-decoration: none;
  letter-spacing: -0.02em;
  flex-shrink: 0;
}
.navbar__logo:hover { color: var(--clr-gold-dim); text-decoration: none; }
.logo-star { color: var(--clr-gold); font-size: 1.1em; }

.navbar__menu ul {
  list-style: none;
  display:    flex;
  gap:        var(--sp-sm);
}

.nav-link {
  color:        var(--clr-on-muted);
  font-size:    0.9rem;
  font-weight:  500;
  padding:      0.35rem 0.65rem;
  border-radius: var(--r-md);
  transition:   color var(--t-fast), background var(--t-fast);
  text-decoration: none;
}
.nav-link:hover, .nav-link:focus-visible {
  color:       var(--clr-gold);
  background:  rgba(245,197,24,0.08);
  text-decoration: none;
}

/* Hamburger toggle (mobile) */
.navbar__toggle {
  display:        none;
  flex-direction: column;
  gap:            5px;
  background:     none;
  border:         none;
  cursor:         pointer;
  padding:        6px;
}
.navbar__toggle span {
  display:    block;
  width:      24px;
  height:     2px;
  background: var(--clr-on-surface);
  border-radius: var(--r-full);
  transition: var(--t-fast);
}

/* ═══════════════════════════════════════════════════════════
   4. BUTTONS
   ═══════════════════════════════════════════════════════════ */
.btn {
  display:         inline-flex;
  align-items:     center;
  gap:             0.4rem;
  padding:         0.7rem 1.6rem;
  border-radius:   var(--r-full);
  font-family:     var(--font-family);
  font-size:       0.95rem;
  font-weight:     600;
  cursor:          pointer;
  border:          2px solid transparent;
  transition:      all var(--t-fast);
  text-decoration: none;
}

.btn--primary {
  background: var(--clr-gold);
  color:      #1a1200;
}
.btn--primary:hover, .btn--primary:focus-visible {
  background:  var(--clr-gold-dim);
  color:       #000;
  box-shadow:  0 0 20px rgba(245,197,24,0.4);
  text-decoration: none;
}

.btn--ghost {
  background:   transparent;
  color:        var(--clr-on-surface);
  border-color: var(--clr-violet);
}
.btn--ghost:hover, .btn--ghost:focus-visible {
  background:  rgba(139,92,246,0.12);
  color:       var(--clr-on-surface);
  box-shadow:  0 0 16px rgba(139,92,246,0.25);
  text-decoration: none;
}

.btn--sm { padding: 0.4rem 1rem; font-size: 0.85rem; }

/* ═══════════════════════════════════════════════════════════
   5. HERO SECTION
   ═══════════════════════════════════════════════════════════ */
.hero {
  position:   relative;
  padding:    var(--sp-xl) 0;
  text-align: center;
  overflow:   hidden;
}

.hero__bg-glow {
  position:         absolute;
  inset:            0;
  background:       radial-gradient(ellipse at 50% 0%, rgba(245,197,24,0.12) 0%, transparent 60%);
  pointer-events:   none;
}

.hero__content { position: relative; z-index: 1; }

.hero__eyebrow {
  margin-bottom: var(--sp-xs);
  color: var(--clr-gold);
}

.hero__title {
  font-size:      clamp(2.5rem, 7vw, 5rem);
  font-weight:    800;
  letter-spacing: -0.03em;
  line-height:    1.05;
  margin-bottom:  var(--sp-sm);
  color:          var(--clr-on-surface);
}

.hero__subtitle {
  font-size:     clamp(1rem, 2vw, 1.25rem);
  color:         var(--clr-on-muted);
  max-width:     600px;
  margin-inline: auto;
  margin-bottom: var(--sp-lg);
}

.hero__ctas {
  display:         flex;
  gap:             var(--sp-sm);
  justify-content: center;
  flex-wrap:       wrap;
}

/* ═══════════════════════════════════════════════════════════
   6. STAT CARDS
   ═══════════════════════════════════════════════════════════ */
.stats-section { padding: var(--sp-lg) 0; }

.stats-grid {
  display:               grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap:                   var(--sp-md);
}

.stat-card {
  background:    var(--clr-glass-card);
  backdrop-filter: blur(12px);
  border:        1px solid var(--clr-glass-border);
  border-top:    1px solid rgba(245,197,24,0.25);
  border-radius: var(--r-lg);
  padding:       var(--sp-lg) var(--sp-md);
  text-align:    center;
  transition:    transform var(--t-med), box-shadow var(--t-med);
}
.stat-card:hover {
  transform:  translateY(-4px);
  box-shadow: 0 0 30px rgba(245,197,24,0.15);
}
.stat-card--violet { border-top-color: rgba(139,92,246,0.4); }
.stat-card--violet:hover { box-shadow: 0 0 30px rgba(139,92,246,0.2); }

.stat-card__icon { font-size: 2rem; margin-bottom: var(--sp-xs); }

.stat-card__number {
  font-size:      2.4rem;
  font-weight:    800;
  letter-spacing: -0.02em;
  color:          var(--clr-gold);
  line-height:    1;
  margin-bottom:  0.25rem;
}

.stat-card__label {
  font-size:    0.85rem;
  color:        var(--clr-on-muted);
  font-weight:  500;
}

/* ═══════════════════════════════════════════════════════════
   7. RESEARCH QUESTION CARDS
   ═══════════════════════════════════════════════════════════ */
.rq-section { padding: var(--sp-lg) 0 var(--sp-xl); }

.section-title {
  font-size:      clamp(1.5rem, 3vw, 2.2rem);
  font-weight:    800;
  letter-spacing: -0.02em;
  margin-bottom:  0.5rem;
}
.section-sub {
  color:         var(--clr-on-muted);
  margin-bottom: var(--sp-lg);
}

.rq-grid {
  display:               grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap:                   var(--sp-md);
}

.rq-card {
  background:    var(--clr-glass-card);
  border:        1px solid var(--clr-glass-border);
  border-radius: var(--r-lg);
  padding:       var(--sp-md);
  display:       flex;
  flex-direction: column;
  gap:           0.5rem;
  text-decoration: none;
  color:         var(--clr-on-surface);
  transition:    transform var(--t-med), box-shadow var(--t-med), border-color var(--t-med);
  position:      relative;
  overflow:      hidden;
}
.rq-card::before {
  content:    '';
  position:   absolute;
  inset:      0;
  background: linear-gradient(135deg, rgba(245,197,24,0.04) 0%, transparent 60%);
  opacity:    0;
  transition: opacity var(--t-med);
}
.rq-card:hover {
  transform:    translateY(-5px);
  box-shadow:   0 0 35px rgba(245,197,24,0.18);
  border-color: rgba(245,197,24,0.3);
  text-decoration: none;
  color:        var(--clr-on-surface);
}
.rq-card:hover::before { opacity: 1; }
.rq-card:focus-visible {
  outline:       2px solid var(--clr-gold);
  outline-offset: 2px;
}

.rq-card__icon  { font-size: 2rem; }
.rq-card__tag   { color: var(--clr-gold); margin-bottom: 0; }
.rq-card__title { font-size: 1.15rem; font-weight: 700; }
.rq-card__desc  { font-size: 0.9rem; color: var(--clr-on-muted); flex: 1; }

.rq-card__arrow {
  align-self:  flex-end;
  font-size:   1.3rem;
  color:       var(--clr-gold);
  transition:  transform var(--t-fast);
}
.rq-card:hover .rq-card__arrow { transform: translateX(4px); }

/* ═══════════════════════════════════════════════════════════
   8. PAGE HERO (for sub-pages)
   ═══════════════════════════════════════════════════════════ */
.page-hero {
  padding:  var(--sp-lg) 0;
  position: relative;
  overflow: hidden;
}
.page-hero::after {
  content:    '';
  position:   absolute;
  inset:      0;
  pointer-events: none;
}
.page-hero--gold::after  { background: radial-gradient(ellipse at 30% 50%, rgba(245,197,24,0.09)  0%, transparent 65%); }
.page-hero--violet::after{ background: radial-gradient(ellipse at 70% 50%, rgba(139,92,246,0.12)   0%, transparent 65%); }
.page-hero--teal::after  { background: radial-gradient(ellipse at 50% 50%, rgba(73,219,255,0.09)   0%, transparent 65%); }

.page-hero .container { position: relative; z-index: 1; }
.page-hero__tag   { color: var(--clr-gold); margin-bottom: 0.5rem; }
.page-hero__title {
  font-size:      clamp(1.8rem, 4vw, 3rem);
  font-weight:    800;
  letter-spacing: -0.02em;
  margin-bottom:  0.5rem;
}
.page-hero__desc  { color: var(--clr-on-muted); max-width: 650px; }

/* ═══════════════════════════════════════════════════════════
   9. CONTENT SECTION & FILTER BAR
   ═══════════════════════════════════════════════════════════ */
.content-section { padding: var(--sp-lg) 0 var(--sp-xl); }

.filter-bar {
  display:     flex;
  align-items: center;
  flex-wrap:   wrap;
  gap:         var(--sp-xs);
  margin-bottom: var(--sp-lg);
  background:  var(--clr-surface);
  padding:     var(--sp-sm) var(--sp-md);
  border-radius: var(--r-lg);
  border:      1px solid var(--clr-glass-border);
}

.filter-bar__label {
  font-size:   0.9rem;
  color:       var(--clr-on-muted);
  white-space: nowrap;
}

.filter-bar__input {
  background:    var(--clr-bg);
  border:        1px solid var(--clr-glass-border);
  border-radius: var(--r-md);
  padding:       0.4rem 0.75rem;
  color:         var(--clr-on-surface);
  font-family:   var(--font-family);
  font-size:     0.9rem;
  width:         90px;
  transition:    border-color var(--t-fast);
}
.filter-bar__input:focus {
  outline:       none;
  border-color:  var(--clr-gold);
  box-shadow:    0 0 0 3px rgba(245,197,24,0.15);
}
.filter-bar__input--sm { width: 70px; }

/* ═══════════════════════════════════════════════════════════
   10. CHARTS
   ═══════════════════════════════════════════════════════════ */
.chart-wrap {
  background:    var(--clr-glass-card);
  border:        1px solid var(--clr-glass-border);
  border-radius: var(--r-lg);
  padding:       var(--sp-md);
  margin-bottom: var(--sp-lg);
  height:        400px;
  position:      relative;
}
.chart-wrap--tall { height: 480px; }

/* ═══════════════════════════════════════════════════════════
   11. DATA TABLES
   ═══════════════════════════════════════════════════════════ */
.table-wrap {
  overflow-x:    auto;
  border-radius: var(--r-lg);
  border:        1px solid var(--clr-glass-border);
}

.data-table {
  width:           100%;
  border-collapse: collapse;
  font-size:       0.9rem;
}

.data-table thead tr {
  background:    var(--clr-surface-hi);
  border-bottom: 1px solid var(--clr-glass-border);
}
.data-table th {
  padding:      0.75rem 1rem;
  text-align:   left;
  font-size:    0.75rem;
  font-weight:  600;
  letter-spacing: 0.07em;
  text-transform: uppercase;
  color:        var(--clr-on-muted);
  white-space:  nowrap;
}

.data-table tbody tr {
  border-bottom: 1px solid var(--clr-glass-border);
  transition:    background var(--t-fast);
}
.data-table tbody tr:last-child { border-bottom: none; }
.data-table tbody tr:hover { background: rgba(245,197,24,0.04); }

.data-table td {
  padding:     0.7rem 1rem;
  color:       var(--clr-on-surface);
  vertical-align: middle;
}

.data-table--compact th,
.data-table--compact td { padding: 0.5rem 0.75rem; }

.rank-cell {
  font-weight: 700;
  color:       var(--clr-on-muted);
  width:       3rem;
}

.genre-list-cell {
  font-size: 0.82rem;
  color:     var(--clr-on-muted);
  max-width: 320px;
}

/* Badges */
.rating-badge {
  display:       inline-flex;
  align-items:   center;
  gap:           0.25rem;
  padding:       0.2rem 0.55rem;
  border-radius: var(--r-full);
  font-size:     0.82rem;
  font-weight:   600;
  background:    rgba(255,255,255,0.06);
  border:        1px solid var(--clr-glass-border);
}
.rating-badge--gold   { background: rgba(245,197,24,0.15); border-color: rgba(245,197,24,0.3); color: var(--clr-gold); }
.rating-badge--green  { background: rgba(73,219,255,0.10); border-color: rgba(73,219,255,0.3); color: var(--clr-teal); }
.rating-badge--default{ color: var(--clr-on-muted); }

.runtime-badge {
  display:       inline-flex;
  padding:       0.2rem 0.55rem;
  border-radius: var(--r-full);
  font-size:     0.82rem;
  font-weight:   600;
  background:    rgba(73,219,255,0.12);
  border:        1px solid rgba(73,219,255,0.25);
  color:         var(--clr-teal);
}

/* ═══════════════════════════════════════════════════════════
   12. DIRECTOR CARDS
   ═══════════════════════════════════════════════════════════ */
.director-grid {
  display:               grid;
  grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
  gap:                   var(--sp-md);
  margin-bottom:         var(--sp-lg);
}

.director-card {
  background:    var(--clr-glass-card);
  border:        1px solid var(--clr-glass-border);
  border-radius: var(--r-lg);
  padding:       var(--sp-md);
  transition:    transform var(--t-med), box-shadow var(--t-med);
}
.director-card:hover {
  transform:  translateY(-4px);
  box-shadow: 0 0 25px rgba(139,92,246,0.2);
}

.director-card__rank {
  font-size:    0.75rem;
  font-weight:  700;
  color:        var(--clr-violet);
  letter-spacing: 0.08em;
  margin-bottom: 0.5rem;
}
.director-card__name {
  font-size:    1.05rem;
  font-weight:  700;
  margin-bottom: var(--sp-sm);
}
.director-card__stats {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap:     0.5rem var(--sp-sm);
}
.director-card__stat {
  display:        flex;
  flex-direction: column;
  gap:            0.15rem;
}
.stat-label { font-size: 0.68rem; color: var(--clr-on-muted); }
.stat-value { font-size: 1.1rem; font-weight: 700; }

/* ═══════════════════════════════════════════════════════════
   13. VERSATILE DIRECTOR CARDS
   ═══════════════════════════════════════════════════════════ */
.versatile-grid {
  display:               grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap:                   var(--sp-md);
  margin-bottom:         var(--sp-lg);
}

.versatile-card {
  background:    var(--clr-glass-card);
  border:        1px solid var(--clr-glass-border);
  border-radius: var(--r-lg);
  padding:       var(--sp-md);
  transition:    transform var(--t-med), box-shadow var(--t-med);
}
.versatile-card:hover {
  transform:  translateY(-3px);
  box-shadow: 0 0 24px rgba(139,92,246,0.18);
}

.versatile-card__header {
  display:     flex;
  align-items: flex-start;
  gap:         var(--sp-xs);
  margin-bottom: 0.75rem;
}
.rank-badge {
  background:    rgba(245,197,24,0.15);
  color:         var(--clr-gold);
  border:        1px solid rgba(245,197,24,0.3);
  border-radius: var(--r-sm);
  padding:       0.1rem 0.4rem;
  font-size:     0.75rem;
  font-weight:   700;
  flex-shrink:   0;
  margin-top:    0.2rem;
}
.versatile-card__name    { font-size: 1rem; font-weight: 700; }
.versatile-card__meta    { display: flex; flex-wrap: wrap; gap: 0.4rem; margin-bottom: 0.75rem; }
.versatile-card__genres  { font-size: 0.82rem; color: var(--clr-on-muted); line-height: 1.5; }

.meta-chip {
  display:       inline-flex;
  align-items:   center;
  gap:           0.2rem;
  padding:       0.2rem 0.55rem;
  border-radius: var(--r-full);
  font-size:     0.78rem;
  font-weight:   600;
  background:    rgba(255,255,255,0.06);
  border:        1px solid var(--clr-glass-border);
}
.meta-chip--gold   { background: rgba(245,197,24,0.12); border-color: rgba(245,197,24,0.25); color: var(--clr-gold); }
.meta-chip--violet { background: rgba(139,92,246,0.12); border-color: rgba(139,92,246,0.25); color: #c4abff; }

/* ═══════════════════════════════════════════════════════════
   14. ABOUT PAGE
   ═══════════════════════════════════════════════════════════ */
.about-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
  gap: var(--sp-md);
}

.about-card {
  background:    var(--clr-glass-card);
  border:        1px solid var(--clr-glass-border);
  border-radius: var(--r-lg);
  padding:       var(--sp-md);
  display:       flex;
  flex-direction: column;
  gap:           var(--sp-sm);
}

.about-card__title {
  font-size:    1.15rem;
  font-weight:  700;
  margin-bottom: 0.25rem;
}

.about-rq-list {
  list-style:   decimal;
  padding-left: var(--sp-md);
  display:      flex;
  flex-direction: column;
  gap:          0.4rem;
  font-size:    0.92rem;
}

.about-note {
  font-size: 0.85rem;
  color:     var(--clr-on-muted);
}

.schema-list {
  list-style:   none;
  display:      flex;
  flex-direction: column;
  gap:          0.5rem;
  font-size:    0.9rem;
}
.schema-list li::before { content: '→ '; color: var(--clr-gold); }

code {
  font-family:   'Courier New', monospace;
  font-size:     0.85em;
  background:    rgba(245,197,24,0.1);
  color:         var(--clr-gold);
  padding:       0.1em 0.4em;
  border-radius: var(--r-sm);
}

/* ═══════════════════════════════════════════════════════════
   15. ERROR PAGE
   ═══════════════════════════════════════════════════════════ */
.error-page {
  min-height:      60vh;
  display:         flex;
  align-items:     center;
  justify-content: center;
  padding:         var(--sp-xl) 0;
}
.error-page__inner { text-align: center; }
.error-page__code  {
  font-size:      8rem;
  font-weight:    800;
  letter-spacing: -0.04em;
  line-height:    1;
  background:     linear-gradient(135deg, var(--clr-gold), var(--clr-violet));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
  margin-bottom:  var(--sp-sm);
}
.error-page__title   { font-size: 1.5rem; margin-bottom: 0.5rem; }
.error-page__message { color: var(--clr-on-muted); margin-bottom: var(--sp-lg); }

/* ═══════════════════════════════════════════════════════════
   16. EMPTY STATE
   ═══════════════════════════════════════════════════════════ */
.empty-state {
  background:    var(--clr-surface);
  border:        1px dashed var(--clr-outline);
  border-radius: var(--r-lg);
  padding:       var(--sp-xl);
  text-align:    center;
  color:         var(--clr-on-muted);
}

/* ═══════════════════════════════════════════════════════════
   17. FOOTER
   ═══════════════════════════════════════════════════════════ */
.footer {
  margin-top:    var(--sp-xl);
  border-top:    1px solid var(--clr-glass-border);
  background:    var(--clr-surface-lo);
}
.footer__inner {
  display:               grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap:                   var(--sp-lg);
  padding:               var(--sp-lg) var(--sp-md);
}
.footer__brand strong {
  font-size:    1.1rem;
  font-weight:  800;
  color:        var(--clr-gold);
  display:      flex;
  align-items:  center;
  gap:          0.4rem;
}
.footer__sub   { font-size: 0.82rem; color: var(--clr-on-muted); margin-top: 0.25rem; }
.footer__heading {
  font-size:    0.72rem;
  font-weight:  600;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  color:        var(--clr-on-muted);
  margin-bottom: 0.75rem;
}
.footer__links ul { list-style: none; display: flex; flex-direction: column; gap: 0.4rem; }
.footer__links a  { font-size: 0.88rem; color: var(--clr-on-muted); }
.footer__links a:hover { color: var(--clr-gold); }
.footer__dataset p { font-size: 0.88rem; color: var(--clr-on-muted); }
.footer__quote {
  margin-top: 0.75rem;
  font-style: italic;
  font-size:  0.82rem;
  color:      var(--clr-outline);
  line-height: 1.5;
}
.footer__bottom {
  text-align:  center;
  padding:     var(--sp-sm) var(--sp-md);
  border-top:  1px solid var(--clr-glass-border);
  font-size:   0.8rem;
  color:       var(--clr-outline);
}

/* ═══════════════════════════════════════════════════════════
   18. RESPONSIVE BREAKPOINTS
   ═══════════════════════════════════════════════════════════ */
@media (max-width: 768px) {
  .navbar__toggle { display: flex; }

  .navbar__menu {
    display:    none;
    position:   absolute;
    top:        70px;
    left:       0;
    right:      0;
    background: rgba(15,15,26,0.95);
    backdrop-filter: blur(20px);
    border-bottom: 1px solid var(--clr-glass-border);
    padding:    var(--sp-sm) var(--sp-md);
  }
  .navbar__menu.is-open { display: block; }
  .navbar__menu ul { flex-direction: column; }
  .nav-link { display: block; padding: 0.6rem 0; }

  .about-grid { grid-template-columns: 1fr; }

  .director-grid,
  .versatile-grid { grid-template-columns: 1fr; }

  .chart-wrap      { height: 320px; }
  .chart-wrap--tall{ height: 380px; }

  .filter-bar { flex-direction: column; align-items: flex-start; }
}

@media (max-width: 480px) {
  .hero { padding: var(--sp-lg) 0; }
  .hero__ctas { flex-direction: column; align-items: center; }
  .stats-grid { grid-template-columns: 1fr; }
}

/* ═══════════════════════════════════════════════════════════
   19. ANIMATIONS
   ═══════════════════════════════════════════════════════════ */
.fade-in {
  opacity:   0;
  transform: translateY(20px);
  transition: opacity 0.5s ease, transform 0.5s ease;
}
.fade-in.is-visible {
  opacity:   1;
  transform: translateY(0);
}

/* Active nav link */
.nav-link--active {
  color:      var(--clr-gold) !important;
  background: rgba(245,197,24,0.08);
}
